using SlothEnterprise.ProductApplication.Applications;
using SlothEnterprise.ProductApplication.Products;
using SlothEnterprise.ProductApplication.ServiceResults;

namespace SlothEnterprise.ProductApplication.ProductHandling.Handlers
{
    public class UnsupportedProductHandler : IProductHandler
    {
        public bool CanHandle(IProduct product)
        {
            return true;
        }

        public ServiceResult SubmitApplicationFor(ISellerApplication application)
        {
            return new ServiceResult(
                id: 1, // generated by something
                code: 2, // lets say this means it's not critical. Probably could be an enum
                errorMessage: "Unsupported product type");
        }
    }
}